version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - pg-network
